qor5/admin

example/hack/build-app.sh
example/hack/build-deploy-app.sh
example/plantbuild/build.jsonnet

https://theplanttokyo.atlassian.net/browse/SRE-2770

add build prod script

---

pagebuilder/example/containers/list_content_lite.go
pagebuilder/example/containers/list_content_with_image.go
pagebuilder/example/containers/page_title.go
pagebuilder/example/containers/tag.go

https://github.com/qor5/admin/pull/5

fix example containers listeditor

---

go.mod
go.sum
presets/examples/setup.go

Upgrade qor5/ui to move stripeui

---

plantbuild/build.jsonnet
plantbuild/images.jsonnet

https://theplanttokyo.atlassian.net/browse/SRE-2830

qor5 push to public registry

---

presets/integration/fields_test.go

https://github.com/qor5/admin/pull/31#issuecomment-1373174216

fix field test

---

example/admin/auth.go
example/admin/config.go
example/admin/router.go
example/admin/user_config.go
example/main.go

https://github.com/qor5/admin/pull/36

remove example url prefix patch

---

hack/build-deploy-app.sh
hack/get-tools.sh

https://theplanttokyo.atlassian.net/browse/SRE-2908

Trigger qor5-provisioning github actions

---

hack/build-deploy-app.sh

https://theplanttokyo.atlassian.net/browse/SRE-2908

fix wrong plantbuild alias

---

example/admin/config.go
example/cmd/publisher/main.go
example/dev_env

https://theplant.slack.com/archives/CL5EY1M6C/p1675672950399529

Bucket to publish pages

---

example/admin/config.go
example/cmd/publisher/main.go

https://theplant.slack.com/archives/CL5EY1M6C/p1676266802008239

Config publish bucket ACL

---

example/admin/user_config.go
role/config.go

https://theplanttokyo.atlassian.net/browse/QOR5-22

Fix missing new role on user editing page

---

example/models/category.go
example/models/l10n_model.go
example/models/l10n_model_with_version.go
example/models/list_model.go
example/models/post.go
example/models/product.go
microsite/microsite.go
pagebuilder/models.go
pagebuilder/publish.go

https://theplanttokyo.atlassian.net/browse/QOR5-55

Implement permRNer to version and l10n resource

---

presets/listing.go
presets/presets.go

https://theplanttokyo.atlassian.net/browse/QOR5-79

Fix pagination after search

---

pagebuilder/builder.go

https://theplant.slack.com/archives/C02B1UQD1JM/p1678696012308569

Hide publish url when page status is not online

---

activity/activity_log.go
activity/activity_model.go
example/admin/config.go
example/admin/perm.go
example/admin/user_config.go

https://theplanttokyo.atlassian.net/browse/QOR5-80

Manager can only view own logs and protect demo account

---

example/admin/profile.go

https://theplanttokyo.atlassian.net/browse/QOR5-88
https://theplanttokyo.atlassian.net/browse/QOR5-91

demo account restrictions

---

presets/gorm2op/operator.go
presets/gormop/operator.go

https://theplanttokyo.atlassian.net/browse/QOR5-118

Add support wildcard search on listing

---

pagebuilder/builder.go

https://theplanttokyo.atlassian.net/browse/QOR5-109

Fix category drop box overflow on page

---

pagebuilder/builder.go

https://theplanttokyo.atlassian.net/browse/QOR5-110

fix shared container republish all pages dup records

---

pagebuilder/example/containers/common.go
pagebuilder/example/containers/heading.go

https://theplanttokyo.atlassian.net/browse/QOR5-38

fix heading font color

---

example/cmd/data-resetor/main.go
media/media_library/media_library.go
media/views/filechooser.go
media/views/list.go
media/views/media_box.go
media/views/messages.go

https://theplanttokyo.atlassian.net/browse/QOR5-122

Optimize media library

---

.github/workflows/go.yml

https://theplanttokyo.atlassian.net/browse/SRE-3213

Add db for go test

---

example/admin/config.go
presets/gorm2op/operator.go
presets/gormop/operator.go

Revert "Fix sql errors in searching for non-text fields"

---

example/admin/data_init.go
l10n/builder.go
pagebuilder/builder.go
pagebuilder/helper.go
pagebuilder/models.go
pagebuilder/publish.go

```
drop table page_builder_categories;
CREATE TABLE "page_builder_categories" ("id" bigserial,"created_at" timestamptz,"updated_at" timestamptz,"deleted_at" timestamptz,"name" text,"path" text,"description" text,"locale_code" text DEFAULT '',PRIMARY KEY ("id","locale_code"))
CREATE INDEX IF NOT EXISTS "idx_page_builder_categories_deleted_at" ON "page_builder_categories" ("deleted_at")
```

Category l10n

---

example/main.go

https://github.com/golang/go/blob/0a17b2c174dcbe0f30a19be2ca5517ed0660f706/src/net/http/pprof/pprof.go#L93-L99

new mux to avoid default net/http/pprof impact

---

go.mod
go.sum

https://github.com/qor5/ui/pull/43

upgrade qor5/ui

---

go.mod
go.sum

https://github.com/qor5/web/pull/45

upgrade web

---

pagebuilder/builder.go

Due to the modifications to `SetterFunc`: https://github.com/qor5/admin/pull/155.

Fix pb category setter func

---

presets/editing.go

https://theplanttokyo.atlassian.net/browse/QOR5-194

fix the issue where the version name does not update immediately

---

presets/editing.go

Revert "fix the issue where the version name does not update immediately"

---

slug/field.go

the auto sync doesn't work properly after unchecking "auto sync from ..."

fix slug auto sync don't work properly

---

example/admin/auth.go
example/admin/login_views.go
example/admin/middlewares.go
example/admin/router.go
example/models/user.go

Remove the "accept subscription emails" form after sign-in.
The form is no longer needed as we will not keep public users data.

remove oauth complete info page

---

seo/collection.go
seo/model.go

Corrected the erroneous comments.
Fixed the bug where the `GetLocale` function of QorSEOSetting should return the `LocaleCode` prop instead of the `Name` prop.

fix some mistakes in comment and a little bug

---

go.mod
go.sum
presets/listing.go

upgrade ui for fixing the issue

fixed the issue where empty datas were returned after executing filter

---

presets/section.go
publish/builder.go

Section only allow edit and hover element if obj.status is draft

feat: section element hover and edit

---

pagebuilder/builder.go
publish/version_compo.go

Feat: VersionDialog allow all permission default

Feat: VersionDialog allow all permission default

---

presets/const.go
publish/version_event.go

Use duplicate perm instead of create perm when duplicate

feat Add duplicate perm

---

presets/detailing.go
presets/section.go

field inject info to support i18n
add section label

Feat section support i18n, add section label

---

example/admin/config.go
media/builder.go
media/media_box.go

Feat Media use AutoMigrate() instead of disAutoMigrate

Feat Media use AutoMigrate() instead of disAutoMigrate

---

example/integration/perm_test.go
presets/detailing.go
presets/section.go

section show edit button when it have update permission.
save func will check update permission too

feat: Add section update permission

---

docs/docsrc/examples/examples_admin/publish.go
docs/docsrc/examples/examples_admin/publish_test.go
publish/version_compo.go

fix version dialog perm wrong
example :  urlName: a-b
current perm: a-b_version_list_dialog
fixed     perm: a_b_version_list_dialog

Fix: version dialog perm wrong

---

docs/docsrc/examples/examples_presets/detailing_inline_edit.go
docs/docsrc/examples/examples_presets/detailing_test.go
docs/docsrc/examples/examples_presets/mux.go
presets/section.go

Section validator only show GlobalError

Section validator only show GlobalError

---

presets/section.go

List Section validator only show GlobalError

List Section validator only show GlobalError

---

docs/docsrc/examples/examples_presets/detailing_test.go
docs/docsrc/examples/examples_presets/editing.go
docs/docsrc/examples/examples_presets/editing_test.go
docs/docsrc/examples/examples_presets/mux.go
presets/editing.go

Set editing error message timeout 2000

Set editing error message timeout 2000

---

docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
docs/docsrc/examples/examples_presets/detailing_inline_edit.go
presets/section.go

feat: Rename section ValidateFunc

---

presets/presets.go

refer: https://theplanttokyo.atlassian.net/browse/KAK-3304
Notice: fix commit comes from 2 projects ( qor5/x and qor5/admin), don't forget to update this two dependencies in Kak project.

fix: 🐛 fix menu scrolling problem

---

docs/docsrc/examples/examples_presets/detailing_inline_edit.go
docs/docsrc/examples/examples_presets/detailing_test.go
presets/field.go

Support field section title i18n

Support field section title i18n

---

docs/docsrc/examples/examples_presets/detailing_inline_edit.go
docs/docsrc/examples/examples_presets/detailing_test.go

Add more section label i18n test

Add more section label i18n test

---

presets/section.go

fix: Add add row i18n

---

presets/messages.go

i18n: Modify New i18n

---

presets/presets.go

https://theplant.slack.com/archives/C05GQCN90D9/p1723168303123829?thread_ts=1722996935.021609&cid=C05GQCN90D9

feat: add extra menu icon to support kakuyasu(cs/cms)admin

---

docs/docsrc/examples/examples_presets/detailing_test.go
docs/docsrc/examples/examples_presets/perm_role_test.go
presets/detailing.go
presets/field.go
presets/field_defaults.go
presets/integration/fields_test.go
presets/presets.go
presets/section.go

- 排除了非自己提交的代码
- 根据review要求修改了 setContainerClass 的命名问题
- 恢复了disableBtn的逻辑

Feat UI reborn

---

example/admin/config.go
example/integration/post_test.go

Fix example post edit body wrong

Fix example post edit body wrong

---

docs/docsrc/examples/examples_presets/listing.go
docs/docsrc/examples/examples_presets/listing_test.go
docs/docsrc/examples/examples_presets/messages.go
presets/listing_compo.go

Support listing button label i18n

Support listing button label i18n

---

presets/section.go

Fix edit section will duplicate portal

Fix section duplicate portal

---

docs/docsrc/examples/examples_presets/detailing_test.go
presets/section.go

click cancel edit display wrong section title

Fix cancel edit display wrong section title

---

publish/messages.go

Fix delete version message JP wrong

Fix delete version message JP wrong

---

activity/timeline.go
presets/const.go
publish/version_compo.go
publish/version_listener.go

publish: disable button on editing && activity: reset data changed on mounted

---

docs/docsrc/examples/examples_presets/detailing_inline_edit.go
docs/docsrc/examples/examples_presets/detailing_test.go
presets/section.go
utils/testflow/gentool/go.mod
utils/testflow/gentool/go.sum

Fix section list create wrong with nil value

Fix section list create wrong with nil value

---

docs/docsrc/examples/examples_presets/detailing_inline_edit.go
docs/docsrc/examples/examples_presets/detailing_test.go
presets/detailing.go
presets/section.go

Refactor section save func

---

presets/menu_order.go

Refactor create menu

---

go.mod
go.sum

https://theplanttokyo.atlassian.net/browse/KAK-5694

chore: update the version of x

---

docs/docsrc/examples/examples_presets/menu.go
docs/docsrc/examples/examples_presets/menu_test.go
docs/docsrc/examples/examples_presets/mux.go
presets/menu_order.go

Fix menu group item permission

Fix menu group item permission

---

pagebuilder/page.go

https://github.com/qor5/admin/blob/main/pagebuilder/models.go#L82

Fix the Page Builder versions count

---

docs/docsrc/examples/examples_presets/detailing_inline_edit.go
docs/docsrc/examples/examples_presets/detailing_test.go
docs/docsrc/examples/examples_presets/mux.go
presets/section.go

Fix section edit button unclickable

Fix section edit button unclickable

---

hack/build-deploy-app.sh
plantbuild/build.jsonnet
plantbuild/images.jsonnet

- **Revert "remove example ci/cd"**
- **Revert "only remain docs"**

restore qor5 example

---

pagebuilder/editor.go

- 支持page-builder 按钮折叠
- 拖拽卡顿优化

feat: support  https://theplanttokyo.atlassian.net/browse/QOR5-412

---

example/admin/demo_case.go
presets/section.go

Not set every field when creating, but set them in detailing

Add section validate only used in detailing

---

pagebuilder/page.go

Remove useless
Fix pageBuilder validator wrong when save section

Fix pageBuilder validator wrong when save section

---

pagebuilder/editor.go
pagebuilder/model.go
presets/editing.go

- https://theplanttokyo.atlassian.net/browse/QOR5-514
- https://theplanttokyo.atlassian.net/browse/QOR5-527

fix: the wrapper border size not accurate

---

pagebuilder/editor.go

https://theplanttokyo.atlassian.net/browse/QOR5-412

fix: oversize right drawer init width and resize case

---

go.mod
go.sum

Upgrade the qor5/x dependency to the latest version for improved functionality and performance.

Update qor5/x to v3.0.14-0.20250120070648-ccf65b4ed1c1

---

presets/listing_compo.go
presets/section.go

https://theplanttokyo.atlassian.net/browse/QOR5-857

fix: add margin classes to HTML components for improved layout

---

go.mod
go.sum

https://theplanttokyo.atlassian.net/browse/QOR5-942

fix-qor5-952

---

docs/docsrc/examples/examples_presets/listing.go
presets/listing_builder.go
presets/listing_compo.go

- Modified the DataTableFunc signature in ListingBuilder to accept a pagination parameter.
- Updated PresetsListingDatatableFunc to utilize the new pagination component in the returned HTML structure.
- Adjusted dataTable method in ListingCompo to pass pagination to the dataTableFunc when defined.

refactor: update DataTableFunc to include pagination component
